---
title: "lab_red_0227"
author: "xm"
date: "February 27, 2020"
output: html_document
---
```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This document contains both instructions and processes needed to process HDDM self-reports data from REDcap. 

Part 0: Table of Content
*need to edit*

Part 1: To-do list


```{r Archive, include=FALSE}

```



```{r Loading, include=FALSE}
#setup the environment: install related packages 

#install.packages("dplyr")
#install.packages("PerformanceAnalytics") #not available for R version 3.4.3
#install.packages("ggplot2")
#install.packages("tidyverse")
#install.packages("stringr")
#install.packages("naniar")
#install.packages("xlsx")

library(dplyr)
#library(PerformanceAnalytics)
library(ggplot2)
library(stringr)
library(naniar)
library(readxl)
# Write the first data set in a new workbook
write.xlsx(clean, file = "myworkbook.xlsx",
      sheetName = "USA-ARRESTS", append = FALSE)
```



```{r Import, include=FALSE}
testing <- read_excel("/Users/xiaoma/Documents/PVDM_office/yeekeh/f_209_1.xlsx")
head(testing)
#need to rename the file, so that trial is not repeatedly used
#maybe python can call and run R script?
#need to output the file too

clean <- testing %>%
  mutate(sep_trial = 
           ifelse(!is.na(trial), as.numeric(trial) +1, 
           ifelse(block < 2.5, 1, 51)),  #depends on block num too
         real_trial = 
           ifelse(block < 1.5, sep_trial, 
           ifelse(block < 2.5, sep_trial + 51, 
           ifelse(block < 3.5, sep_trial + 52, sep_trial+103)))
         ) %>%
  select(sub, block, Btype, real_trial, img1, img2, RESP, RT)
#View(clean)
```

```{r Output, include=FALSE}

write.csv(clean,"/Users/xiaoma/Documents/PVDM_office/yeekeh/f_209_1_output.xlsx", row.names = TRUE)

```

